// Generated by gencpp from file sim_grasp/sim_graspModel.msg
// DO NOT EDIT!


#ifndef SIM_GRASP_MESSAGE_SIM_GRASPMODEL_H
#define SIM_GRASP_MESSAGE_SIM_GRASPMODEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sim_grasp
{
template <class ContainerAllocator>
struct sim_graspModel_
{
  typedef sim_graspModel_<ContainerAllocator> Type;

  sim_graspModel_()
    : x(0)
    , y(0)
    , z(0.0)
    , grasp_depth(0.0)
    , angle(0.0)
    , width(0.0)  {
    }
  sim_graspModel_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0.0)
    , grasp_depth(0.0)
    , angle(0.0)
    , width(0.0)  {
  (void)_alloc;
    }



   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _grasp_depth_type;
  _grasp_depth_type grasp_depth;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::sim_grasp::sim_graspModel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sim_grasp::sim_graspModel_<ContainerAllocator> const> ConstPtr;

}; // struct sim_graspModel_

typedef ::sim_grasp::sim_graspModel_<std::allocator<void> > sim_graspModel;

typedef boost::shared_ptr< ::sim_grasp::sim_graspModel > sim_graspModelPtr;
typedef boost::shared_ptr< ::sim_grasp::sim_graspModel const> sim_graspModelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sim_grasp::sim_graspModel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sim_grasp::sim_graspModel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sim_grasp::sim_graspModel_<ContainerAllocator1> & lhs, const ::sim_grasp::sim_graspModel_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.grasp_depth == rhs.grasp_depth &&
    lhs.angle == rhs.angle &&
    lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sim_grasp::sim_graspModel_<ContainerAllocator1> & lhs, const ::sim_grasp::sim_graspModel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sim_grasp

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_grasp::sim_graspModel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sim_grasp::sim_graspModel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_grasp::sim_graspModel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "301be63e53b935edf2f7fc2376d5d03a";
  }

  static const char* value(const ::sim_grasp::sim_graspModel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x301be63e53b935edULL;
  static const uint64_t static_value2 = 0xf2f7fc2376d5d03aULL;
};

template<class ContainerAllocator>
struct DataType< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sim_grasp/sim_graspModel";
  }

  static const char* value(const ::sim_grasp::sim_graspModel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# x, y: 抓取点的像素坐标 (x, y)\n"
"# z: 抓取点的深度距离，单位 米\n"
"# grasp_depth: 抓取深度,实际抓取点距离物体表面的深度\n"
"# angle: 抓取弧度角 [0, 2π]\n"
"# width: 抓取宽度,单位米\n"
"\n"
"uint16 x\n"
"uint16 y\n"
"float64 z\n"
"float64 grasp_depth\n"
"float64 angle\n"
"float64 width\n"
;
  }

  static const char* value(const ::sim_grasp::sim_graspModel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.grasp_depth);
      stream.next(m.angle);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sim_graspModel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sim_grasp::sim_graspModel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sim_grasp::sim_graspModel_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "grasp_depth: ";
    Printer<double>::stream(s, indent + "  ", v.grasp_depth);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIM_GRASP_MESSAGE_SIM_GRASPMODEL_H
