# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sim_grasp/sim_graspModel.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sim_graspModel(genpy.Message):
  _md5sum = "301be63e53b935edf2f7fc2376d5d03a"
  _type = "sim_grasp/sim_graspModel"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# x, y: 抓取点的像素坐标 (x, y)
# z: 抓取点的深度距离，单位 米
# grasp_depth: 抓取深度,实际抓取点距离物体表面的深度
# angle: 抓取弧度角 [0, 2π]
# width: 抓取宽度,单位米

uint16 x
uint16 y
float64 z
float64 grasp_depth
float64 angle
float64 width
"""
  __slots__ = ['x','y','z','grasp_depth','angle','width']
  _slot_types = ['uint16','uint16','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,grasp_depth,angle,width

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sim_graspModel, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.z is None:
        self.z = 0.
      if self.grasp_depth is None:
        self.grasp_depth = 0.
      if self.angle is None:
        self.angle = 0.
      if self.width is None:
        self.width = 0.
    else:
      self.x = 0
      self.y = 0
      self.z = 0.
      self.grasp_depth = 0.
      self.angle = 0.
      self.width = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H4d().pack(_x.x, _x.y, _x.z, _x.grasp_depth, _x.angle, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.x, _x.y, _x.z, _x.grasp_depth, _x.angle, _x.width,) = _get_struct_2H4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H4d().pack(_x.x, _x.y, _x.z, _x.grasp_depth, _x.angle, _x.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.x, _x.y, _x.z, _x.grasp_depth, _x.angle, _x.width,) = _get_struct_2H4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H4d = None
def _get_struct_2H4d():
    global _struct_2H4d
    if _struct_2H4d is None:
        _struct_2H4d = struct.Struct("<2H4d")
    return _struct_2H4d
